### ISSUE TITLE
[build] undefined reference to AddClipboardFormatListener | Define WINVER?

### ISSUE THREAD

**Issue by DoumanAsh** [retep998/winapi-rs#171]
Some functions requires to have speicfiic windows versions.
By default in (gcc)winuser.h:
```
#ifndef WINVER
#define WINVER 0x0502
#endif
```

Due to that for example AddClipboardFormatListener() will not work as there will be no reference in header, though it is available starting from Vista

I believe that winver is defined only in windows headers, but not sure what's approach should be in case of gcc

As of current my build fails like that:
``` undefined reference to `AddClipboardFormatListener' ```

GCC 4.9.2 winuser.h:
```
#if WINVER >= 0x0600
  WINUSERAPI WINBOOL WINAPI AddClipboardFormatListener (HWND hwnd);
  WINUSERAPI WINBOOL WINAPI RemoveClipboardFormatListener (HWND hwnd);
  WINUSERAPI WINBOOL WINAPI GetUpdatedClipboardFormats (PUINT lpuiFormats, UINT cFormats, PUINT pcFormatsOut);
#endif
```

**Comment by retep998** [comment]
If you do not reference a function in your code then the symbol will be unreferenced and the linker will not attempt to link it. The undefined reference is NOT an issue with headers or the operating system version. Rather the issue is that the import libraries you have do not provide that symbol. Mingw's libraries are notorious for not having symbols from newer versions of Windows.

Now if you _do_ link a symbol and then attempt to run your binary on a version of Windows that doesn't provide that function, your program will crash on startup with an error about being unable to find that symbol. I intend to eventually provide a way to delay load functions with a way to handle the case that the operating system doesn't provide the symbol.

**Comment by DoumanAsh** [comment]
Aww.. i see. I didn't consider that mingw would fail me like that :)
Sorry
