### ISSUE TITLE
What does the 100% unsafe badge mean?

### ISSUE THREAD

**Issue by johnthagen** [retep998/winapi-rs#366]
I'm curious what the https://img.shields.io/badge/unsafe-100%25-blue.svg (unsafe 100%) meant in the README. At first glance I thought it might calculate the percentage of `unsafe` LOC, but then I saw it was just statically set in the URL.

**Comment by retep998** [comment]
People are always pushing for crates to use less unsafe code, and recently someone even created a service which did measure the percentage of safe code. Because winapi is raw bindings so it is unsafe to use, measuring the safety of it didn't really make sense. As a result, the 100% unsafe badge is satire of that "make everything 100% safe Rust" movement.

https://www.reddit.com/r/rust/comments/5l0kv7/check_the_safety_of_a_rust_crate_on_github/dbs2hnt/
