### ISSUE TITLE
Any interest in abstracting away encoding conversion and unsafe pointer access?

### ISSUE THREAD

**Issue by mqudsi** [retep998/winapi-rs#419]
I've only been working with rust off-and-on over the years, but I'm wondering if there's any interest in abstracting away the encoding conversion between UTF-8 and UTF-16 for `xxxxW` function calls in `winapi-rust`?

Is there a technical, rusty reason why this example from the README:

	fn print_message(msg: &str) -> Result<i32, Error> {
		let wide: Vec<u16> = OsStr::new(msg).encode_wide().chain(once(0)).collect();
		let ret = unsafe {
			MessageBoxW(null_mut(), wide.as_ptr(), wide.as_ptr(), MB_OK)
		};
	}

cannot look like this:

	fn print_message(msg: &str) -> Result<i32, Error> {
		let ret = unsafe {
			MessageBoxW(null_mut(), &str, &str, MB_OK)
		};
	}

or even like this:

	fn print_message(msg: &str) -> Result<i32, Error> {
		MessageBoxW(null_mut(), &str, &str, MB_OK)
	}

abstracting away the unsafe memory access as well?
I understand this example is somewhat basic and the `unsafe` block might be required for other functions and in the name of consistency it makes more sense just to keep it everywhere. But the string conversion?

**Comment by retep998** [comment]
Right now `MessageBoxW` is a simple extern function. When you call it, you are directly calling the function provided by `user32.dll`. In order to do what you want, a wrapper function would have to be written that performs various conversions. Writing such wrapper functions would require a lot of manual effort for every single function and is out of the scope of winapi. There's nothing stopping anyone from writing their own wrappers around winapi, so there's no need for winapi to do that itself.

Related issue: https://github.com/retep998/winapi-rs/issues/298
