### ISSUE TITLE
type of SOCKET has changed in 0.3

### ISSUE THREAD

**Issue by dimbleby** [retep998/winapi-rs#534]
The `SOCKET` defined [here](https://github.com/retep998/winapi-rs/blob/70e1da884554825a084bea0f9762dc1f91b51c93/src/um/winsock2.rs#L44) no longer agrees with the `SOCKET` defined by the [standard library](https://github.com/rust-lang/rust/blob/b1363a73ede57ae595f3a1be2bb75d308ba4f7f6/src/libstd/sys/windows/ext/raw.rs#L18-L21).

That's because you now define `UINTPTR` simply as `usize`, where it used to be either `c_uint` or `__uint64`.

I see this because I try to use `::winapi::um::winsock2::INVALID_SOCKET` where a `::std::os::windows::io::RawSocket` is expected: this was fine at 0.2, but at 0.3 I get "expected u64, found usize" errors.

No doubt I can cast my way around this, but I thought I should draw it to your attention in case you weren't aware of it.  

Does this library even need its own definition of a `SOCKET`?  The current situation of two not-quite-duplicate definitions seems sub-optimal.

**Comment by retep998** [comment]
`winapi` supports `#![no_std]` therefore it cannot rely on definitions from `std`. Using `usize` for pointer sized types is intentional. `libc` has been moving towards using `usize` for pointer sized types, so I assume `SOCKET` would be defined as `usize` in `std` if they had the chance to break backwards compatibility.
