### ISSUE TITLE
Winapi 0.3 socket regressions

### ISSUE THREAD

**Issue by keeperofdakeys** [retep998/winapi-rs#540]
I'm trying to migrate socket2-rs to winapi 0.3, but I'm running into a few issues.

1. The `sockaddr_in6` type doesn't exist, though it looks like this [has already been reported](https://github.com/retep998/winapi-rs/issues/533).
2. The `winapi::um::winsock2::SOCKET` definition now maps to `usize` instead of `u64`, however the rust stdlib uses `u64` for `std::os::windows::raw::SOCKET`. This type is used in some traits (like `std::os::windows::io::IntoRawSocket`). I'm not sure of the best way to fix this, I could cast to u64 when calling those traits?
3. In order to build a `winapi::shared::inaddr::in_addr` I need a `in_addr_S_un`, however the `UNION!` macro appears to make the type private, so I get this error when trying to construct one:
```
constructor is not visible here due to private fields
did you mean `in_addr_S_un { /* fields */ }`?
```
The `UNION!` macro should either add an impl for From/Into, or mark the field as public.

**Comment by retep998** [comment]
1. Switch to `SOCKADDR_IN6` as soon as the next version is published.
2. Using `usize`/`isize` for pointer sized types is intentional. It is unfortunate that this doesn't match up with what `std` does, but oh well. Just cast as needed. https://github.com/retep998/winapi-rs/issues/534
3. Unions cannot be initialized directly. You have to initialize them using `mem::zeroed()` and then assign the value you want using one of the mutable variant methods.

**Comment by keeperofdakeys** [comment]
Thanks for the help, I've got this working now. Are you planning on making a new release with the SOCKADDR_IN6_LH struct included in the next few weeks?

**Comment by retep998** [comment]
I'll publish a new version soon.
