### ISSUE TITLE
Would it be possible to implement default trait for structs

### ISSUE THREAD

**Issue by Invisible-Rabbit-Hunter** [retep998/winapi-rs#556]
I was wondering if it would be possible to implement the default trait for the structures in the library, making it easier to only set the fields actually required? That would allow people to avoid using unsafe blocks and `std::mem::zeroed()`.

**Comment by retep998** [comment]
Adding `Default` impls causes a significant increase in compile time, and also cannot be done easily because some types don't support deriving `Default`. `std::mem::zeroed()` works well enough and given the tradeoffs, I will not be adding `Default` impls. *However*, I may consider adding some way in the future to mark that the types can be zero initialized safely (especially if libcore added such a trait).

**Comment by Invisible-Rabbit-Hunter** [comment]
Ok... Thank you for explaining and now I understand.
