### ISSUE TITLE
COleDropTarget Class

### ISSUE THREAD

**Issue by dannyfritz** [retep998/winapi-rs#627]
I'm looking at adding file drag hover and exit events to `winit`. https://github.com/tomaka/winit/issues/448

It appears I need `winapi` to have the [`COleDropTarget class`](https://docs.microsoft.com/en-us/cpp/mfc/reference/coledroptarget-class).

Adding this class will require a fairly complex web of other classes within MFC and so on so forth. I'm willing to put the effort into adding this and submitting a PR. Just need a little direction on where to start or what might be a similar example class to look at.

**Comment by dannyfritz** [comment]
Alright, I was alerted that MFC is outside the scope of `winapi`. If this isn't the case, please reopen this issue.

**Comment by retep998** [comment]
At the moment due to `COleDropTarget` being part of MFC and not part of Windows API, I am not likely to accept such a PR. What you may actually be interested in however is [`IDropTarget`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679679(v=vs.85).aspx) which is the actual underlying COM interface used by `COleDropTarget` allowing you to skip a whole mess of C++ wrappers.
