### ISSUE TITLE
Why does this libary not contain WriteConsole function?

### ISSUE THREAD

**Issue by TimonPost** [retep998/winapi-rs#634]
On the Microsoft site, there is documentation about the [WriteConsole ](https://docs.microsoft.com/en-us/windows/console/writeconsole) function. 

Writes a character string to a console screen buffer beginning at the current cursor location. Why does this library not contain the WriteConsole function?

**Comment by MSxDOS** [comment]
WriteConsole is not a function but a macro that expands to either an ANSI or Unicode variant of an actual function. See [Conventions for Function Prototypes](https://msdn.microsoft.com/en-us/library/windows/desktop/dd317766(v=vs.85).aspx). As per CONTRIBUTING:

> Definitions which depend on whether UNICODE is defined should not be included. It is the user's responsibility to explicitly choose between W and A functions (and they should always choose W).

Now, if the library is actually missing something that it should have then it's because it either hasn't been added (yet) or is impossible to implement in the minimum Rust version required to be supported by the library which is currently 1.6

**Comment by retep998** [comment]
???
https://docs.rs/winapi/*/x86_64-pc-windows-msvc/winapi/um/consoleapi/fn.WriteConsoleW.html
https://docs.rs/winapi/*/x86_64-pc-windows-msvc/winapi/um/consoleapi/fn.WriteConsoleA.html
???
