### ISSUE TITLE
HMONITOR is an empty enum - results in illegal instruction

### ISSUE THREAD

**Issue by SuperCuber** [retep998/winapi-rs#662]
While using the api I tried to get a handle to the primary monitor in order to `SetMonitorColorTemperature` on it, however I found out that `winapi::shared::windef::HMONITOR` is a pointer to an empty enum.

Returning such a value from a function is UB and of course results in an illegal instruction with this example code:
```rust
unsafe {
    let primary_monitor = MonitorFromPoint(POINT { x: 0, y: 0 }, MONITOR_DEFAULTTOPRIMARY);
    match *primary_monitor {}
}
```

Seems to me like the issue lies in [this definition](https://docs.rs/winapi/0.3.5/x86_64-pc-windows-msvc/winapi/shared/windef/enum.HMONITOR__.html), it should be compatible with the input [here](https://docs.rs/winapi/0.3.5/x86_64-pc-windows-msvc/winapi/um/highlevelmonitorconfigurationapi/fn.SetMonitorColorTemperature.html), and it obviously isn't.

**Comment by retep998** [comment]
Raw pointers to empty enums are completely legal and not UB. It's only if you turn it into a reference or dereference it in any way that you run into issues but you should **never** dereference a handle. There is no reason you should ever be doing `match *primary_monitor {}` and you wouldn't be able to do that in safe Rust anyway because that would require dereferencing a raw pointer, which again you should not be doing for handles.

Please note that you cannot pass an `HMONITOR` directly to `SetMonitorColorTemperature`. You must first use `GetPhysicalMonitorsFromHMONITOR` to turn the `HMONITOR` into a `HANDLE`.

**Comment by SuperCuber** [comment]
@retep998 Thanks, that works.
