### ISSUE TITLE
wParam of LL_KEYBOARD can not be compared to WM_KEYUP

### ISSUE THREAD

**Issue by flip111** [retep998/winapi-rs#690]
https://msdn.microsoft.com/en-us/library/ms644985(v=VS.85).aspx

```
wParam [in]
Type: WPARAM

The identifier of the keyboard message. This parameter can be one of the following messages: WM_KEYDOWN, WM_KEYUP, WM_SYSKEYDOWN, or WM_SYSKEYUP.
```

In cpp you can do `if (wParam == WM_KEYUP) {`

In rust you get type error
```
error[E0308]: mismatched types
  --> src\main.rs:42:39
   |
42 |   if wParam == WM_KEYUP {
   |                ^^^^^^^^ expected usize, found u32
```

WM_KEYUP is defined in `winapi::um::winuser`

**Comment by retep998** [comment]
The `WM_` constants are given the type `UINT` because they are typically used with functions like `GetMessage` and `SendMessage` which use `UINT` for that parameter, and I am stuck with choosing only one type for those constants because Rust does not have generic constants. In C and C++ that comparison works because of implicit integer coercion, but in Rust such casts must be done explicitly.

There is no bug in `winapi` here. You're just running into a limitation of Rust, and you'll have to do some casts in order to compare those values.

**Comment by flip111** [comment]
Thanks for explanation @retep998 

Here is a blog post discussing the use of the `Into` trait http://benashford.github.io/blog/2015/05/24/rust-traits-for-developer-friendly-libraries/ and here another page talking about it https://news.ycombinator.com/item?id=9600834

Is this possibly something that can be used to let `SetWindowsHookExW` accept a callback with a different type signature so that `wParam` can be made of type `u32`

**Comment by retep998** [comment]
No. `SetWindowsHookExW` is an external function that I have no control over and has very specific requirements over what the type signature is. If you change the type signature of the callback, it won't match what the hook system expects when it calls your callback, and all sorts of lovely undefined behavior could occur.

**Comment by flip111** [comment]
Understood.
I find the `Into` trait very interesting though .. perhaps there is a way to leverage it in other parts of the code to make the api more smoother (i have not found any such part as of now though).

**Comment by retep998** [comment]
Remember that these are raw bindings to whatever Windows API provides. Safer higher level wrappers taking advantage of things like `Into` are the responsibility of *other* crates.

**Comment by flip111** [comment]
Are there any of such crates right now? Perhaps adding a module with higher level construct to this crate would be nice at some point in the future. But i understand if you don't want to extend the scope of the project.

**Comment by retep998** [comment]
There are plenty of crates wrapping specific areas, but Windows API is simply **massive** so there's a ton of API surface that isn't wrapped yet. It being massive is always why I'm not going to add higher level stuff to this crate because it's already enough work just creating the raw bindings in the first place (only a fraction of Windows API is even bound yet!) and to add higher level wrappers to everything would takes ***ages*** and probably murder compile time as well.
