### ISSUE TITLE
Crate is empty in non-windows targets

### ISSUE THREAD

**Issue by gnzlbg** [retep998/winapi-rs#712]
Why is the crate empty in non-windows targets ? Shouldn't that be a compilation error ?

Since one can use target-dependent dependencies, I think it is weird to allow depending on `winapi` on targets that cannot support it (an extra crate to download in those targets, for no real reason). 

I was looking to how to solve this problem in the `mach` crate (like `winapi` for macosx), and was actually going to propose solving it in the opposite direction.

**Comment by retep998** [comment]
Because it's not always feasible or practical to guarantee that you depend on `winapi` only on Windows. For a long time cargo did not have any way to make dependencies conditional on cfgs, only allowing you to restate the dependencies over and over for each individual target. As a result many crates used to depend on `winapi` unconditionally, and having `winapi` be an empty crate on non-Windows platforms was very convenient.

Nowadays it's not as much of an issue, but what is there to gain from making `winapi` potentially break someone's build? So what if someone ends up downloading a crate that they don't really need? That's not a good enough reason to make it a hard error!

**Comment by gnzlbg** [comment]
> So what if someone ends up downloading a crate that they don't really need? That's not a good enough reason to make it a hard error!

I was just asking because I was wondering what libraries like winapi should do (I was pondering making `mach` just hard error on this in the next release). Your comment seems to indicate that the only reason you twinapi does it this way is historical. If you could change this without breaking anybody, would you do so ?

**Comment by gnzlbg** [comment]
Also related question: what is it there to gain by allowing winapi to compile for all targets ?

**Comment by retep998** [comment]
The minimum version of Rust that `winapi` supports does not support cfg conditional dependencies. So while it may seem like a historical reason, it's actually still relevant to this day. Also I'm not about to stop anyone from downloading `winapi` when they don't need to because it makes my download counter go up on crates.io.

**Comment by gnzlbg** [comment]
> Also I'm not about to stop anyone from downloading winapi when they don't need to because it makes my download counter go up on crates.io.

Damn, I forgot about this :D 

> The minimum version of Rust that winapi supports does not support cfg conditional dependencies.

But this is a really good reason.
