### ISSUE TITLE
I need IDesktopWallpaper::SetWallpaper

### ISSUE THREAD

**Issue by MOZGIII** [retep998/winapi-rs#722]
Hello, as suggested in the readme, I'm creating this issue.

I need a way to use `IDesktopWallpaper::SetWallpaper` (https://docs.microsoft.com/en-us/windows/desktop/api/shobjidl_core/nf-shobjidl_core-idesktopwallpaper-setwallpaper).

I think I need to use is via COM, but I don't know if it's currently possible, and if it is - how to do it.

Thanks.

**Comment by retep998** [comment]
Once bindings have been added it should be possible. The class `DesktopWallpaper` implements the `IDesktopWallpaper` interface, so you can just use `CoCreateInstance` to get a `IDesktopWallpaper` object and then call the `SetWallpaper` method on it.

**Comment by MOZGIII** [comment]
So, the first step is bindings. Can you give me a code example of how can I create the bindings? Should it be a PR to this repo, or are they supposed to live in my own code base?

https://docs.rs/winapi/0.3.6/winapi/um/combaseapi/fn.CoCreateInstance.html - is this the call you're talking about?

**Comment by retep998** [comment]
Because `IDesktopWallpaper` is defined in the Windows SDK, you would submit a PR to this repo adding it.

It lives in `um/shobjidl_core.h` in the Windows SDK and the equivalent module in this crate already exists and has some examples in it: https://github.com/retep998/winapi-rs/blob/0.3/src/um/shobjidl_core.rs

`CONTRIBUTING.md` has a lot of useful information.

**Comment by lberrymage** [comment]
Since this functionality was merged in #745, I think we can close this issue.
