### ISSUE TITLE
advapi32-sys 0.1.2 has * dependencies

### ISSUE THREAD

**Issue by sugar700** [retep998/winapi-rs#861]
I would recommend yanking advapi32-sys 0.1.0 to 0.1.2, and releasing 0.1.3 which is essentially the same as 0.1.2, but without `*` dependencies, using real supported versions instead.

Alternatively, yank 0.1.* without releasing 0.1.3, it's not that anyone is using 0.1 anyway.

This causes issues with `-Z minimal-versions` builds (https://github.com/rust-lang/cargo/issues/5657).

**Comment by retep998** [comment]
0.1.* of advapi32-sys is already broken and won't build even without `-Z minimal-versions` because it'll try to depend on winapi 0.3 which is very different from the winapi 0.2 it was written against. Anyone who is still using advapi32-sys should already be on 0.2.0. There's nobody left who would use 0.1.3.

If I start yanking old versions of advapi32-sys I'd have to also start yanking all the old versions of the other winapi -sys crates, and that's a really long process with how many there are. Maybe in the future I can go on a crusade of yanking but for now there's nothing actionable to be done here.

**Comment by kornelski** [comment]
To be clear, this isn't about actual users of v0.1, which there are none. It's about `minimal-versions` picking 0.1 just because it exists, and other crates weren't specifying their dependencies correctly (e.g. because other crates used `advapi32-sys = "*"` to get 0.2, or `winapi = "0"` or such).

I've asked several people to yank problematic versions, but most tell me "I won't yank it, because it's just an old version that nobody uses", and don't care or appreciate that `minimal-versions` picks these old versions, and they _are_ used by accident.

Until these old unused crates are yanked, `minimal-versions` will be unusable and the whole feature is at risk of being removed :(
