### ISSUE TITLE
Question: How to call GetMonitorInfoW with an LPMONITORINFOEXW

### ISSUE THREAD

**Issue by patriksvensson** [retep998/winapi-rs#901]
Thanks for a great library!

I'm currently trying to enumerate all monitors using the `GetMonitorInfoW` function. According to [MSDN documentation](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfow) I should be able to use a `LPMONITORINFO` pointing to either a `MONITORINFO` or `MONITORINFOEX` as long as I set `cbSize` to the correct size.

Gettings a `MONITORINFO` is no problem, but I have no idea how to get a `MONITORINFOEX` (or in this case `MONITORINFOEXA`).

How do I accomplish this using winapi?

**Comment by retep998** [comment]
If you're calling `GetMonitorInfoW` you should use `MONITORINFOEXW` not `MONITORINFOEXA`.

Using `MONITORINFOEXW` instead of `MONITORINFO` should be fairly simple. Change the type of your variable from `MONITORINFO` to `MONITORINFOEXW` and when you call `GetMonitorInfoW` you cast the pointer by doing `<*mut _>::cast(&mut monitor_info)`. To retrieve the string from the `MONITORINFOEXW` you first calculate the length by looking for the first 0 in the array, and then pass the sliced down version to `OsString::from_wide`.

**Comment by patriksvensson** [comment]
@retep998 The `MONITORINFOEXA` was a typo, and casting as you suggested worked like a charm. Thanks!
